language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm

sudo: true

matrix:
  allow_failures:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: nightly
    - php: hhvm
  fast_finish: true

before_install:
  - composer self-update --no-interaction
  - composer --version --no-interaction

env:
  - PREFER_LOWEST="--prefer-lowest"
  - PREFER_LOWEST=""

before_script:
  - composer update --ignore-platform-reqs --prefer-dist $PREFER_LOWEST
  - composer --optimize-autoloader --no-interaction

script:
  - bin/phpunit --configuration . --coverage-clover=build/logs/clover.xml --coverage-html=build/html/coverage

after_script:
  - if [ $(phpenv version-name) == "5.6" ] && [ "$PREFER_LOWEST" == "--prefer-lowest" ]; then bin/codacycoverage clover build/logs/clover.xml > /dev/null 2>&1; fi

after_success:
  # Push coverage to github pages branch
  - chmod +x ./update-gh-pages.sh
  - if [ $(phpenv version-name) == "5.6" ] && [ "$PREFER_LOWEST" == "--prefer-lowest" ]; then bash ./update-gh-pages.sh; fi
  # CREATE GIT TAG
  - git config --global user.email "builds@travis-ci.org"
  - git config --global user.name "Travis"
  - export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d")-$TRAVIS_BUILD_NUMBER
  - echo -n $GIT_TAG > public/version
  - git commit -m "Set build VERSION number" public/version
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push --tags --quiet https://$GITHUBKEY@github.com/clickalicious/webserver-daemon > /dev/null 2>&1

# Blacklist the pushed tag from above to prevent black hole
branches:
  except:
    - /^build-[0-9a-z\-]*/

# Who to notify?
notifications:
  slack:
    secure: HixCatOvGrTEhzQ2qfUXpAx4trTNj3WcaFbsHoT36DNb1gczofga4dvXwzHc9ntIvUpYftq7FN9Fb1ja5Ek5h4tRlBzeLW8cy9KgZJVYX7Akx5dInhZI/8sYumYB2BsH55x/dr8ASctmnoN2JPHkacZ0ejQZel21sI/FlPVVl31EOKYYBV2aN/LBXW6HuxzbNBpcDlRPAlIKE+FkZ6p89b8cJiOsC01deNRJN66w0obOlq88zbDlkDg8zBmGE+KlyQWOg4ZY1GYhVlCUDd9u2ilnMQBzp1QfzMsD0E65RJSED9vUcLfwEnA3XKYawcHo7WuqFne7JKxK9p30Q0TQeNTAdKSZq4o0RiY1a1Tsl0sRZYVhFtCV4DqtgPtswPaIwA56wc3fjNTiU4OnR6tVcfdMiZPGZ4d+Hckms3DLhrcEGykp2hpJozoh3dE4JUdExmvZE1bNEbgK7sHwsVFtx+P4E9YwV+O1ULxHGFgdNbGx+fHeU9KajwQWTpwJcnPmK0VQfzxf8KWpczvXFapMuizIlRZqsCMVOtPf316/5X2jE3GOQT3K4QrBHWrZEjR6J+bcpA70nDazp5dRZFgso2R0a8ThnIMysuA0QgZMPCSnPrIGI2mSkSUim4xp8V7GViC0QNaqtYWZQMRLvyvk3lo9b5AKL6WE8NweTwRu+CI=
  email:
    recipients:
      - opensource@clickalicious.de
